version: '3'
services:

  db1:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: customers
    volumes:
      - db1_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - test

  db2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: orders
    volumes:
      - db2_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - test

networks:
  test:
    external: true
  internal:
    internal: true

volumes:
  db1_data:
  db2_data:
